#
# .coveralls.yml - configuration file for the coveralls code coverage service
#
# see https://coveralls.io/docs/php for more hints
#
service_name: travis-ci
src_dir: framework
coverage_clover: build/logs/clover.xml
